# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mysql-pv-volumes
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 512Mi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: "/mnt/data"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pv-claims
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 512Mi
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  selector:
    matchLabels:
      app: mysql-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - image: mysql:latest
        name: mysql-db
        env:
        - name: MYSQL_USER
          value: "dd_earl"
        - name: MYSQL_PASSWORD
          value: "password_weather"  
        - name: MYSQL_DATABASE
          value: "weather_database"                    
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password   
        ports:
        - containerPort: 3306    
          # name: mysql-svc
      #   volumeMounts:
      #   - name: mysql-persistent-storage
      #     mountPath: /var/lib/mysql
      # volumes:
      # - name: mysql-persistent-storage
      #   persistentVolumeClaim:
      #     claimName: mysql-pv-claims
      nodeSelector:
        deployment_node: weather_app          
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-db