# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   creationTimestamp: null
#   labels:
#     app: sense-weather-only
#   name: sense-weather-only
#   namespace: staging  
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: sense-weather-only
#   strategy: {}
#   template:
#     metadata:
#       creationTimestamp: null
#       labels:
#         app: sense-weather-only
#     spec:
#       containers:
#       - image: infinitiq502004/raspiweather:5.0
#         name: raspiweather-only
#         resources: {}
#         securityContext:
#           privileged: true
#       nodeSelector:
#         deployment_node: weather_app
# status: {}
# ---
apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: sense-weather-only
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: sense-weather-only
      namespace: staging  
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: infinitiq502004/raspiweather:5.0
            imagePullPolicy: IfNotPresent
            name: raspi-weather-only
            resources: {}
            securityContext:
              privileged: true            
          nodeSelector:
            deployment_node: weather_app
          restartPolicy: OnFailure
  schedule: 0/5 * * * ?
  successfulJobsHistoryLimit: 1
status: {}